name: my first workflow
on: push
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: greet
        run: echo "running my first workflow"
      - name: 2nd step!
        run: echo "another workflow"
      - name: 3rd step
        run: ls
  secondjob:
    runs-on: ubuntu-latest
    steps:
      - name: just add line
        run: echo "added one more line"
