name: multi job flow
on: workflow_dispatch
jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - name: greet
        run: echo "welcome to github actions"
  buildjob:
    runs-on: ubuntu-latest
    steps:
      - name: build the job
        run: echo "welcome to github actions"
  deployjob:
    runs-on: ubuntu-latest
    steps:
      - name: deploy the job
        run: echo "welcome to github actions"
    
